### ISSUE TITLE
[Epic][Design] - XQuery end-user product dashboard overview

### ISSUE THREAD

**Issue by sh-rn** [blocknetdx/xquery-enduser-dashboard#1]
### Scenario:
Hydra and XQuery data consumers should be able to create and manage their projects via a simple and accessible tool.

Users should be able to connect to a SNode on the network, request a new project from that SNode, and manage their Hydra/XQuery projects via a web-based UI. 
Once a project has been requested successfully, the user should be able to administer project payments, monitor data usage and manage their projects via an intuitive, real-time, web-based dashboard.

### To do:
- [x] Design a front end UI that facilitates the easy onboarding to, and usage of, the XQuery product by end-users: https://github.com/blocknetdx/xquery-enduser-dashboard/issues/2
- [x] #3
- [ ] Connect front-end with SNode network (TBD)

### Target audience:
Developers/product managers/biz managers who need access to decentralised blockchain data to power their services or products.

----

### Required UI features:
- [x] List of available snodes with a list of available services
- [x] Project and payment management (TBD)
- [x] Usage monitoring per project and per X period
- [x ] web3-login
- [ ] Embedded analytics to gather usage data for testing purposes
- [x] Maintain the product brand
- [x] Easy access to support materials

### Target Env:
Modern web browsers.

**Comment by shrnkld** [comment]
UI first version (light theme): https://scene.zeplin.io/project/622734263ce07eb47e64d0aa
